remote_theme: riggraz/minimalist-theme

lang: en-US
title: JASPAR Motif Downloader
tagline: "Python GUI for Batch Downloading Human TF Motifs"


theme_mode: dark 

show_downloads: true 
github: [repository_url: "https://github.com/AileenCohen/jaspar-motif-downloader.git"]
