remote_theme: chirpy-theme/jekyll-theme-chirpy

lang: en-US
timezone: Asia/Jerusalem 
title: JASPAR Motif Downloader
tagline: "A Python GUI for Batch Downloading Human TF Motifs"

theme_mode: dark 
accent_color: teal 

aux_links: {}
nav_external_links: {}
