theme: minima

title: JASPAR Motif Downloader
author: Aileen Cohen
description: >- 
  A Python GUI application for searching and performing batch downloads of human
  Transcription Factor (TF) binding motifs from the JASPAR CORE database.
